from django.conf.urls import patterns, url
import views
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns(
    '',
    url(r'^$',
        views.HomepageView.as_view(),
        name="homepage",),
    url(_(r'^bagni/$'),
        views.BagniView.as_view(),
        name="bagni",),
    url(_(r'^bagno/(?P<slug>[-\w]+)/$'),
        views.BagnoView.as_view(),
        name="bagno"),
    url(_(r'^search/$'),
        views.SearchView.as_view(),
        name="search"),
    url(_(r'^service-categories/$'),
        views.ServiceCategoriesView.as_view(),
        name="service-categories"),
    url(_(r'^service-category/(?P<slug>[-\w]+)/$'),
        views.ServiceCategoryView.as_view(),
        name="service-category"),
    url(_(r'^services/$'),
        views.ServicesView.as_view(),
        name="services"),
    url(_(r'^services/(?P<slug>[-\w]+)/$'),
        views.ServiceView.as_view(),
        name="service"),
    url(_(r'^municipality/(?P<slug>[-\w]+)/$'),
        views.MunicipalityView.as_view(),
        name="municipality"),
    url(_(r'^municipalities/$'),
        views.MunicipalitiesView.as_view(),
        name="municipalities"),
    url(_(r'^district/(?P<slug>[-\w]+)/$'),
        views.DistrictView.as_view(),
        name="district"),
    url(_(r'^districts/$'),
        views.DistrictsView.as_view(),
        name="districts"),

    # VISTE TEMPORANEE
    url(_('^globalmap/$'),
        views.GlobalMapView.as_view(),
        name="globalmap"),
    url(_('^benve/$'),
        views.BenveView.as_view(),
        name="benve"),
    url(_('^benve2/$'),
        views.Benve2View.as_view(),
        name="benve2"),
)
